name: Deploy Websites
on: 
  push:
    branches:
      - main
jobs: 
  test:
    runs-on: macos-latest
    steps: 
    - name: Get Code
      uses: actions/checkout@v3 
    - name: cache dependecies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: dep-node-modules-${{ hashFiles('**/package-lock.js') }}
    - name: Install Depedencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: run test
      run: npm run test

  build:
    runs-on: macos-latest
    steps: 
    - name: Get Code
      uses: actions/checkout@v3 
    - name: cache dependecies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: dep-node-modules-${{ hashFiles('**/package-lock.js') }}
    - name: Install Depedencies
      run: npm ci
    - name: Lint Code
      run: npm run lint
    - name: Build Project 
      run: npm run build
  deploy:
    runs-on: macos-latest
    steps: 
    - name: EchoDeploying
      run: echo "Deploying Website..."